# Generated by Django 6.0.2 on 2026-02-22 00:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="projects.costcode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_codes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "baseline_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "revised_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "cost_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="projects.costcode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_lines",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "cost_code__code"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCostRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_type",
                    models.CharField(
                        choices=[("commitment", "Commitment"), ("actual", "Actual")],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "record_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("source_module", models.CharField(blank=True, max_length=60)),
                ("source_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "cost_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_records",
                        to="projects.costcode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_cost_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_records",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-record_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="costcode",
            index=models.Index(
                fields=["project", "is_active"], name="projects_co_project_c8ddf7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="costcode",
            constraint=models.UniqueConstraint(
                fields=("project", "code"), name="projects_cost_code_unique_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="projectbudgetline",
            index=models.Index(
                fields=["project", "cost_code"], name="projects_pr_project_e3a697_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectbudgetline",
            constraint=models.UniqueConstraint(
                fields=("project", "cost_code"),
                name="projects_budget_line_unique_cost_code_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="projectcostrecord",
            index=models.Index(
                fields=["project", "cost_code", "record_type"],
                name="projects_pr_project_db901b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectcostrecord",
            index=models.Index(
                fields=["record_date"], name="projects_pr_record__06a8b7_idx"
            ),
        ),
    ]
