# Generated by Django 6.0.2 on 2026-02-22 11:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_progressbilling_revenuerecognitionentry_and_more"),
        ("projects", "0003_project_closed_at_project_closed_by_changeorder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntryAdjustingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("deferred_revenue", "Deferred Revenue"),
                            ("accrued_expense", "Accrued Expense"),
                            ("depreciation", "Depreciation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalEntryBankReconDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalEntryClosingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.PositiveSmallIntegerField()),
                (
                    "scope",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="yearly",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalEntryCorrectionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalEntryRecurringDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateField(blank=True, null=True)),
                ("run_reference", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("source_module", models.CharField(max_length=120)),
                ("source_event", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "posting_policy",
                    models.CharField(
                        choices=[("immediate", "Immediate"), ("manual", "Manual")],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                (
                    "entry_class",
                    models.CharField(
                        choices=[
                            ("daily_recurring", "Daily Recurring"),
                            ("adjusting", "Adjusting"),
                            ("closing", "Closing"),
                            ("bank_reconciliation", "Bank Reconciliation"),
                            ("correction", "Correction"),
                            ("opening_balance", "Opening Balance"),
                            ("manual", "Manual"),
                            ("operational_auto", "Operational Auto"),
                        ],
                        default="operational_auto",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PostingRuleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_order", models.PositiveIntegerField(default=1)),
                (
                    "side",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("amount_source", models.CharField(blank=True, max_length=180)),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("description_template", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["posting_rule", "line_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecurringEntryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template_code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("next_run_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="KWD", max_length=3)),
                ("auto_post", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["template_code"],
            },
        ),
        migrations.CreateModel(
            name="RecurringEntryTemplateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_order", models.PositiveIntegerField(default=1)),
                (
                    "side",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["template", "line_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="report_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("current_asset", "Current Asset"),
                    ("non_current_asset", "Non Current Asset"),
                    ("current_liability", "Current Liability"),
                    ("non_current_liability", "Non Current Liability"),
                    ("equity", "Equity"),
                    ("operating_revenue", "Operating Revenue"),
                    ("other_revenue", "Other Revenue"),
                    ("operating_expense", "Operating Expense"),
                    ("other_expense", "Other Expense"),
                ],
                default="",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="correction_root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrections",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="currency",
            field=models.CharField(default="KWD", max_length=3),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_class",
            field=models.CharField(
                choices=[
                    ("daily_recurring", "Daily Recurring"),
                    ("adjusting", "Adjusting"),
                    ("closing", "Closing"),
                    ("bank_reconciliation", "Bank Reconciliation"),
                    ("correction", "Correction"),
                    ("opening_balance", "Opening Balance"),
                    ("manual", "Manual"),
                    ("operational_auto", "Operational Auto"),
                ],
                default="manual",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="fx_rate_to_base",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("1.00000000"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-8"))],
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversal_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source_event",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source_module",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source_object_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="journalline",
            name="credit_foreign",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="debit_foreign",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_lines",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="KWD", max_length=3),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("bank_name", models.CharField(max_length=120)),
                ("account_number", models.CharField(blank=True, max_length=80)),
                ("currency", models.CharField(default="KWD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gl_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_accounts",
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement_date", models.DateField()),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("imported", "Imported"),
                            ("reconciled", "Reconciled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="finance.bankaccount",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("is_reconciled", models.BooleanField(default=False)),
                (
                    "matched_journal_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_bank_statement_lines",
                        to="finance.journalline",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.bankstatement",
                    ),
                ),
            ],
            options={
                "ordering": ["statement", "line_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_currency", models.CharField(default="USD", max_length=3)),
                ("to_currency", models.CharField(default="KWD", max_length=3)),
                ("rate_date", models.DateField()),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exchange_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-rate_date", "from_currency", "to_currency"],
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("soft_closed", "Soft Closed"),
                            ("hard_closed", "Hard Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("soft_closed_at", models.DateTimeField(blank=True, null=True)),
                ("hard_closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hard_closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hard_closed_fiscal_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "soft_closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soft_closed_fiscal_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_sessions",
                        to="finance.bankaccount",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_bank_reconciliation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_bank_reconciliation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_reconciliation_sessions",
                        to="finance.fiscalperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="finance.fiscalperiod",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["status", "entry_date"], name="finance_jou_status_8dc373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_class", "entry_date"],
                name="finance_jou_entry_c_280acd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["source_module", "source_event"],
                name="finance_jou_source__6dc063_idx",
            ),
        ),
        migrations.AddField(
            model_name="journalentryadjustingdetail",
            name="journal_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjusting_detail",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentrybankrecondetail",
            name="bank_statement_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciliation_entries",
                to="finance.bankstatementline",
            ),
        ),
        migrations.AddField(
            model_name="journalentrybankrecondetail",
            name="journal_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_recon_detail",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentrybankrecondetail",
            name="reconciliation_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciliation_entries",
                to="finance.bankreconciliationsession",
            ),
        ),
        migrations.AddField(
            model_name="journalentryclosingdetail",
            name="journal_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="closing_detail",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentrycorrectiondetail",
            name="corrected_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correction_details",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentrycorrectiondetail",
            name="journal_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correction_detail",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentryrecurringdetail",
            name="journal_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_detail",
                to="finance.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="postingrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posting_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postingruleline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posting_rule_lines",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="postingruleline",
            name="posting_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="finance.postingrule",
            ),
        ),
        migrations.AddField(
            model_name="recurringentrytemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_entry_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recurringentrytemplate",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_entry_templates",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="journalentryrecurringdetail",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_entries",
                to="finance.recurringentrytemplate",
            ),
        ),
        migrations.AddField(
            model_name="recurringentrytemplateline",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_template_lines",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="recurringentrytemplateline",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="finance.recurringentrytemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatement",
            constraint=models.UniqueConstraint(
                fields=("bank_account", "statement_date"),
                name="finance_bank_statement_unique_per_day_account",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(
                fields=["from_currency", "to_currency", "rate_date"],
                name="finance_exc_from_cu_4c517a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("from_currency", "to_currency", "rate_date"),
                name="finance_exchange_rate_unique_pair_date",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["year", "month"], name="finance_fis_year_69406f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(fields=["status"], name="finance_fis_status_441588_idx"),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="finance_fiscal_period_unique_year_month"
            ),
        ),
        migrations.AddIndex(
            model_name="postingrule",
            index=models.Index(
                fields=["source_module", "source_event", "is_active"],
                name="finance_pos_source__2c4fbf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingrule",
            constraint=models.UniqueConstraint(
                fields=("source_module", "source_event"),
                name="finance_posting_rule_unique_source_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="postingruleline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_source__gt", ""),
                    ("fixed_amount__isnull", False),
                    _connector="OR",
                ),
                name="finance_posting_rule_line_has_amount_source_or_fixed_amount",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringentrytemplate",
            index=models.Index(
                fields=["is_active", "next_run_date"],
                name="finance_rec_is_acti_7db07f_idx",
            ),
        ),
    ]
