# Generated by Django 6.0.2 on 2026-02-22 13:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_journalentryadjustingdetail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watermark_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("text", "Text"),
                            ("image", "Image"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("watermark_text", models.CharField(blank=True, max_length=255)),
                ("watermark_image_url", models.URLField(blank=True)),
                (
                    "watermark_opacity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.12"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                ("watermark_rotation", models.IntegerField(default=-30)),
                (
                    "watermark_scale",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=4
                    ),
                ),
                ("invoice_prefix", models.CharField(default="INV-", max_length=20)),
                ("invoice_padding", models.PositiveIntegerField(default=5)),
                ("invoice_next_number", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Print Settings",
                "verbose_name_plural": "Print Settings",
            },
        ),
    ]
