# Generated by Django 6.0.2 on 2026-02-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sequence_companyprofile_base_currency_and_more"),
        ("finance", "0007_printsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="core.customer",
            ),
        ),
    ]
