# Generated by Django 6.0.2 on 2026-02-22 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_purchaserequest_approved_at_and_more"),
        ("projects", "0002_costcode_projectbudgetline_projectcostrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="cost_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="projects.costcode",
            ),
        ),
    ]
