# Generated by Django 6.0.2 on 2026-02-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_purchaseorderitem_cost_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(default="KWD", max_length=3),
        ),
    ]
