# Generated by Django 6.0.2 on 2026-02-23 08:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_v2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treasurypayment",
            name="channel",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank", "Bank")],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="treasuryreceipt",
            name="channel",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank", "Bank")],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adjustment_number", models.CharField(max_length=40, unique=True)),
                ("adjustment_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Increase"), ("decrease", "Decrease")],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="erp_v2.masteritem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="erp_v2.inventorylocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryCountSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_number", models.CharField(max_length=40, unique=True)),
                ("count_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("completed", "Completed")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_sessions",
                        to="erp_v2.inventorylocation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
