# Generated by Django 6.0.2 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("legal_name", models.CharField(blank=True, default="", max_length=200)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("tax_number", models.CharField(blank=True, default="", max_length=80)),
                ("website", models.URLField(blank=True, default="")),
                ("primary_color", models.CharField(blank=True, default="#0f2a43", max_length=20)),
                ("secondary_color", models.CharField(blank=True, default="#c89b3c", max_length=20)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profile",
            },
        ),
    ]
